language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install requests
  - pip install pyramid
  - pip install numpy
  - pip install coveralls 
script:
  nosetests --with-coverage --cover-package=WebPoller
after_success:
  coveralls
