language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install requests
  - pip install pyramid
  - pip install numpy
  - pip install coveralls 
  - pip install coverage 
script:
  nosetests --with-coverage --cover-package=poller
after_success:
  coveralls
