language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install requests
  - pip install pyramid
  - pip install numpy
  - pip install coverage
script:
  nosetests --with-coverage
after_success:
  coveralls
