// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('ngApp', ['ngResource']);

  app.controller('ListController', function($scope) {});

  app.controller('customersCtrl', function($scope, $http) {
  $http.get("/test").then(function (response) {
      $scope.myData = response.data.records;
  }); })

}).call(this);
